# Generated by Django 3.2 on 2023-01-11 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='is_acive',
            new_name='is_active',
        ),
    ]
